ALTER TABLE Pessoa    --ALTER TABLE
ADD (CACHORRO VARCHAR2(10));

CREATE INDEX pais_fabricacao --CREATE INDEX
on ARMA(Fabricacao);

INSERT INTO pessoa(nome, cpf) VALUES ('Valmir', '082.220.724-19'); -- INSERT INTO

UPDATE arma -- UPDATE
SET Fabricacao = 'EUA'
WHERE Fabricacao = 'Estados Unidos';

DELETE --DELETE
FROM Pessoa
WHERE cpf_pessoa = '082.220.724-19';

SELECT P.NOME, P.CPF, PR.patente -- SELECT, FROM, WHERE
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF;

SELECT P.NOME, P.CPF, PR.patente -- BETWEEN
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF AND PR.PATENTE BETWEEN 3 AND 10;

SELECT P.NOME, P.CPF, PR.patente -- IN
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF AND PR.PATENTE IN (1,2);

SELECT * FROM TELEFONE_BASE -- LIKE
WHERE NUMERO LIKE '(81)%';

SELECT * FROM ENDERECO_BASE -- IS NOT NULL
WHERE NUMERO IS NOT NULL;

SELECT * -- INNER JOIN
FROM PESSOA INNER JOIN MILITAR ON
PESSOA.CPF = MILITAR.CPF;

SELECT MAX(HORARIO_E_DATA) -- MAX
FROM FORNECER_ARMAMENTO;

SELECT MIN(DATA_DE_MANUTENCAO) -- MIN
FROM ARSENAL;

SELECT --AVG
    ROUND(AVG( ALL PATENTE), 2) AVG_PATENTE
FROM MILITAR;

SELECT -- COUNT
    COUNT(CASE WHEN PATENTE >1 THEN 1 END)
FROM MILITAR;

SELECT P.NUMERO_DE_REGISTRO, P.ID_ARSENAL, P.NOME_DO_ARMAMENTO, PR.HORARIO_E_DATA, PR.CPF_MILITAR -- FULL OUTER JOIN
FROM ARMA P FULL OUTER JOIN FORNECER_ARMAMENTO PR ON P.NUMERO_DE_REGISTRO = PR.REGISTRO_ARMA;

SELECT CPF, PATENTE -- SUBCONSULTA COM OPERADOR RELACIONAL
FROM MILITAR
WHERE
    PATENTE> (
        SELECT
            AVG(PATENTE)
            FROM MILITAR
    )
ORDER BY PATENTE;

SELECT NOME_DO_ARMAMENTO, CALIBRE, ID_ARSENAL, FABRICACAO -- SUBCONSULTA COM IN
FROM ARMA
WHERE
  FABRICACAO = 'Estados Unidos' AND NUMERO_DE_REGISTRO IN (SELECT REGISTRO_ARMA FROM FORNECER_ARMAMENTO
    WHERE HORARIO_E_DATA < '20-APR-22 03.30.00.000000 PM');

SELECT CPF, PATENTE -- SUBCONSULTA COM ANY
FROM MILITAR
    WHERE
        CPF = ANY(SELECT CPF_MILITAR FROM VISITANTE);

SELECT P.NOME AS COMANDANTE --SUBCONSULTA COM ALL
FROM MILITAR PR, PESSOA P
WHERE P.CPF = PR.CPF AND PR.PATENTE >= ALL(SELECT PATENTE FROM MILITAR);