ALTER TABLE Pessoa    --ALTER TABLE
ADD (CACHORRO VARCHAR2(10));

CREATE INDEX pais_fabricacao --CREATE INDEX
on ARMA(Fabricacao);

INSERT INTO pessoa(nome, cpf) VALUES ('Valmir', '082.220.724-19'); -- INSERT INTO

UPDATE arma -- UPDATE
SET Fabricacao = 'EUA'
WHERE Fabricacao = 'Estados Unidos';

DELETE --DELETE
FROM Pessoa
WHERE cpf_pessoa = '082.220.724-19';

SELECT P.NOME, P.CPF, PR.patente -- SELECT, FROM, WHERE
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF;

SELECT P.NOME, P.CPF, PR.patente -- BETWEEN
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF AND PR.PATENTE BETWEEN 3 AND 10;

SELECT P.NOME, P.CPF, PR.patente -- IN
FROM PESSOA P, MILITAR PR
WHERE P.CPF = PR.CPF AND PR.PATENTE IN (1,2);

